# I. User
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoYW5odGh1eSIsImlhdCI6MTY3NDcyNTI2MX0.WttXYRfnVlQuZTPqlE9JSdpwsu91t_xYvdYOyQzI7wo
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjkzYTdhNGIxYWRmMWU2OWI1NzQyZCIsInVzZXJuYW1lIjoidGhhbmh0aHV5IiwiZW1haWwiOiJ0aGFuaHRodXlAZ21haWwuY29tIiwiaWF0IjoxNjc1NTczMzIyLCJleHAiOjE2NzU1NzM0NDJ9._159bF_duNIjM1qeMdq28xQ0DT9kjL-0MdeG3BNBF-c
Authorization: Beaer {{token}}



### List All Message
POST http://localhost:3001/api/listMessage
Authorization: Beaer {{token}}
Content-Type: application/json

{
    "senderID": "63b93a7a4b1adf1e69b5742d"
}


###  Message
POST http://localhost:3001/api/message
Authorization: Beaer {{token}}
Content-Type: application/json

{
    "senderID": "63b93a7a4b1adf1e69b5742d",
    "receiverID": "63d5360bbfe103866f4ee972"
}
### login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "thanhthuy",
    "password": "1"
}
### logout
POST http://localhost:3001/api/logout
Content-Type: application/json

{
    "id": "63b93a7a4b1adf1e69b5742d"
}

### refreshToken
POST http://localhost:3001/api/refreshToken
Content-Type: application/json

{
    "id": "63b93a7a4b1adf1e69b5742d",
    "token": "{{refreshToken}}"
}


### search
POST http://localhost:3001/api/user/search
Authorization: Beaer {{token}}
Content-Type: application/json

{
    "username": "khoavh"
}
### register
POST http://localhost:3001/api/register
Content-Type: application/json

{
    "username": "khoavh",
    "email": "khoavh@gmail.com",
    "password": "1",
    "avatar": "https://cdn.diemnhangroup.com/seoulcenter/2022/11/gai-xinh-2.jpg"
}

### Destroy All
DELETE http://localhost:3001/api/user/destroy
Authorization: Beaer {{token}}

### profile
GET http://localhost:3001/api/user/profile/63b673f6f878cb9c68675fe6
Authorization: Beaer {{token}}


###  delete a users
DELETE http://localhost:3001/api/users/delete/63baa329b593996a69735666
Authorization: Beaer {{token}}